name: crud
description: Basic CRUD using dart_frog framework
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_frog: ^0.3.7
  dart_jsonwebtoken: ^2.8.2
  dotenv: ^4.1.0
  encrypt: ^5.0.1
  mongo_dart: ^0.9.1

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
